In [1]:
import numpy as np
np.random.seed(0)

In [6]:
x1 = np.random.randint(10, size=6) # satu dimensi
x2 = np.random.randint(10, size=(3, 4)) # dua dimensi
x3 = np.random.randint(10, size=(3, 4, 5)) # tiga dimensi
print(x1)
print(x2)
print(x3)

[8 1 1 7 9 9]
[[3 6 7 2]
 [0 3 5 9]
 [4 4 6 4]]
[[[4 3 4 4 8]
  [4 3 7 5 5]
  [0 1 5 9 3]
  [0 5 0 1 2]]

 [[4 2 0 3 2]
  [0 7 5 9 0]
  [2 7 2 9 2]
  [3 3 2 3 4]]

 [[1 2 9 1 4]
  [6 8 2 3 0]
  [0 6 0 6 3]
  [3 8 8 8 2]]]


In [9]:
print(x3.ndim) # output berupa tingkatan dimensi
print(x3.shape) # output berupa bentuk dimensi
print(x3.size) # total data keseluruhan

3
(3, 4, 5)
60


In [13]:
print(x3.dtype) # tipe data array

# total ukuran data (dalam byte)

print(x1.nbytes)
print(x2.nbytes)
print(x3.nbytes)

int64
48
96
480
