In [2]:
import numpy as np
np.random.seed(0)

In [3]:
x1 = np.random.randint(10, size=6) # satu dimensi
x2 = np.random.randint(10, size=(3, 4)) # dua dimensi
x3 = np.random.randint(10, size=(3, 4, 5)) # tiga dimensi
print(x1)
print(x2)
print(x3)

[5 0 3 3 7 9]
[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
[[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]


In [9]:
print(x3.ndim) # output berupa tingkatan dimensi
print(x3.shape) # output berupa bentuk dimensi
print(x3.size) # total data keseluruhan

3
(3, 4, 5)
60


In [13]:
print(x3.dtype) # tipe data array

# total ukuran data (dalam byte)

print(x1.nbytes)
print(x2.nbytes)
print(x3.nbytes)

int64
48
96
480


In [17]:
print(x1) # print array 1 dimensi
print(x1[0]) # print array indeks pertama
print(x1[-1]) # print array indeks paling akhir
print(x1[-2]) # print array indeks kedua terakhir

[8 1 1 7 9 9]
8
9
9


In [24]:
print (x2[0, 0]) # print indeks ke 0 0
print (x3[0, 0, 4]) # print indeks ke 0 0 4

3
8


In [3]:
x = np.arange(0, 20)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [12]:
print(x[:5]) # lima element pertama
print(x[5:]) # setelah indeks kelima
print(x[1:3]) # antara indeks 1 sampai 2
print(x[::2]) # tiap indeks ke genap
print(x[1::2]) # tiap indeks ke genap, dimulai dari 1
print(x[::-1]) # print dengan urutan terbalik
print(x[8::-1]) # print terbalik dimulai dari indeks ke 8

[0 1 2 3 4]
[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[1 2]
[ 0  2  4  6  8 10 12 14 16 18]
[ 1  3  5  7  9 11 13 15 17 19]
[19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]
[8 7 6 5 4 3 2 1 0]


Multi dimensi array

In [14]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [23]:
print(x2[:2, :3]) # print 2 x 3 matriks pertama
print(x2[:3, ::2]) # print 3 x 2, matriks dengan indeks row genap
print(x2[::-1, ::-1]) # reverse matriks
# akses kolom pertama
print(x2[0, :])
print(x2[0])

print(x2[:, 0]) # akses baris pertama

[[3 5 2]
 [7 6 8]]
[[3 2]
 [7 8]
 [1 7]]
[[7 7 6 1]
 [8 8 6 7]
 [4 2 5 3]]
[3 5 2 4]
[3 5 2 4]
[3 7 1]


In [5]:
x2_sub = x2[:2, :2] # menyimpan x2 2x2 ke dalam x2_sub
print(x2_sub)

[[3 5]
 [7 6]]


In [6]:
x2_sub[1, 1] = 99 # ikut teredit juga nilai x2 nya
print(x2_sub)
print(x2)

[[ 3  5]
 [ 7 99]]
[[ 3  5  2  4]
 [ 7 99  8  8]
 [ 1  6  7  7]]


In [7]:
x2_sub_copy = x2[:2, :1].copy()
print(x2_sub_copy)

[[3]
 [7]]


In [9]:
x2_sub_copy[0, 0] = 1
print(x2_sub_copy)
print(x2)

[[1]
 [7]]
[[ 3  5  2  4]
 [ 7 99  8  8]
 [ 1  6  7  7]]


Membentuk ulang array

In [10]:
grid = np.arange(1, 10).reshape((3, 3)) # membentuk array 3 x 3 dengan nilai 1 sampai 9
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
x = np.array([1, 2, 3])

x.reshape((1, 3))

array([[1, 2, 3]])

In [13]:
x[np.newaxis, :]

array([[1, 2, 3]])

In [14]:
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [15]:
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [16]:
x = np.array([3, 2, 1])
y = np.array([6, 5, 4])
np.concatenate([x, y]) # menggabungkan dua array

array([3, 2, 1, 6, 5, 4])

In [20]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                [6, 5, 4]])
np.vstack([x, grid]) # menumpuk dua dimensi array secara vertikal

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [21]:
y = np.array([[99],
             [99]])
np.hstack([grid, y]) # menggabungkan array secara horizontal

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

In [24]:
upper, lower = np.vsplit(grid, [1]) # memotong array secara vertikal di indeks 1
print(upper)
print(lower)
left, right = np.hsplit(grid, [1]) # memotong array secara horizontal di indeks 1
print(left)
print(right)

[[9 8 7]]
[[6 5 4]]
[[9]
 [6]]
[[8 7]
 [5 4]]
