Ini untuk versioning numpy

In [2]:
import numpy as np
np.__version__

'1.16.4'

Ini penjabaran list

In [6]:
L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [7]:
type(L[0])

int

In [8]:
L2 = [str(c) for c in L]
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [9]:
type(L2[0])

str

In [11]:
L3 = [True, "2", 3.0, 4]
[type(item) for item in L3]

[bool, str, float, int]

In [12]:
import array
L = list(range(10))
A = array.array('i', L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Ini untuk koding numpy

In [13]:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

Implementasi numpy array dengan tipe integer

In [17]:
np.array([1, 1.8, 3, 4], dtype='int')

array([1, 1, 3, 4])

Numpy array 2 dimensi

In [18]:
np.array([range(i, i+3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [26]:
data = np.full((2,2), 3.14, dtype='float64')
print(data)
print(data[0][0])

[[3.14 3.14]
 [3.14 3.14]]
3.14


In [23]:
np.ones((2,2), dtype='int')

array([[1, 1],
       [1, 1]])

Numpy array berurutan

In [3]:
np.arange(0, 20, 3)

array([ 0,  3,  6,  9, 12, 15, 18])

Numpy array dengan range antara a sampai b sebanyak n-1

In [6]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])