### Numpy Arrays

In [8]:
my_list = [1, 2, 3]

In [9]:
import numpy as np

In [11]:
arr = np.array(my_list)

In [12]:
arr

array([1, 2, 3])

In [14]:
my_mat = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [15]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [20]:
np.zeros(3)

array([0., 0., 0.])

In [22]:
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [23]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [27]:
np.ones(4)

array([1., 1., 1., 1.])

In [28]:
np.linspace(0, 5, 100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [29]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [32]:
np.eye(1)

array([[1.]])

In [33]:
np.random.rand(5)

array([0.9613759 , 0.00329988, 0.22485269, 0.75425762, 0.70691659])

In [34]:
np.random.rand(5, 5)

array([[0.47005591, 0.24419745, 0.81621531, 0.85900831, 0.33534635],
       [0.05783447, 0.70500324, 0.36011452, 0.88940402, 0.93786999],
       [0.01878553, 0.87403077, 0.59202318, 0.62152501, 0.62879192],
       [0.63407207, 0.51355489, 0.60434743, 0.16231169, 0.21340743],
       [0.3928081 , 0.31589293, 0.08500103, 0.74502551, 0.97718165]])

In [37]:
np.random.randn(2)

array([-1.11757217,  0.7071706 ])

In [39]:
np.random.randint(1, 100, 10)

array([ 2, 90,  6, 10, 37, 97, 70, 80, 50, 42])

In [40]:
arr = np.arange(25)

In [41]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [43]:
ranarr = np.random.randint(0, 50, 10)

In [44]:
ranarr

array([27,  2,  8, 27, 40, 18, 35, 14,  3,  1])

In [47]:
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [48]:
ranarr.max()

40

In [49]:
ranarr.min()

1

In [50]:
ranarr.argmax()

4

In [53]:
ranarr.argmin()

9

In [54]:
arr = arr.reshape(5, 5)

In [55]:
arr.shape

(5, 5)

In [56]:
arr.dtype

dtype('int64')

In [57]:
from numpy.random import randint

In [58]:
randint(2, 10)

6